-- V11: Criação das tabelas do domínio legado: cupomauto, documento, geraauto, resposta, embalagem, fiscaladm e geraprodi
-- Schema base
CREATE SCHEMA IF NOT EXISTS app;

-- =========================
-- cupomauto
-- =========================
CREATE SEQUENCE IF NOT EXISTS app.cupomauto_idcupom_seq INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS app.cupomauto (
    id                  INTEGER PRIMARY KEY DEFAULT nextval('app.cupomauto_idcupom_seq'),
    descConformidade    TEXT,
    descPorte           TEXT,
    numeroAuto          INTEGER,
    valorConformidade   TEXT,
    valorGerado         TEXT,
    valorPorte          TEXT,
    numeroConformidade  INTEGER,
    percConformidade    INTEGER,
    percPorte           INTEGER
);

-- =========================
-- documento
-- =========================
CREATE SEQUENCE IF NOT EXISTS app.documento_iddocumento_seq INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS app.documento (
    id          INTEGER PRIMARY KEY DEFAULT nextval('app.documento_iddocumento_seq'),
    descricao   TEXT NOT NULL,
    restricao   INTEGER NOT NULL
);

-- =========================
-- geraauto
-- =========================
CREATE SEQUENCE IF NOT EXISTS app.geraauto_idgeraauto_seq INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS app.geraauto (
    id               INTEGER PRIMARY KEY DEFAULT nextval('app.geraauto_idgeraauto_seq'),
    dataGeraauto     DATE,
    horaGeraauto     TIME,
    idUsuario        INTEGER,
    status           INTEGER,
    numeroProcesso   TEXT,
    tipoPenalidade   TEXT,
    valor            TEXT,
    grauInfracao     INTEGER,
    idTramitacao     INTEGER
);

-- =========================
-- resposta
-- =========================
CREATE SEQUENCE IF NOT EXISTS app.resposta_idresposta_seq INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS app.resposta (
    id             INTEGER PRIMARY KEY DEFAULT nextval('app.resposta_idresposta_seq'),
    dataResposta   TIMESTAMP,
    idforum        INTEGER NOT NULL,
    textoResposta  TEXT,
    CONSTRAINT fk_resposta_forum FOREIGN KEY (idforum) REFERENCES app.forum (id)
);
CREATE INDEX IF NOT EXISTS idx_resposta_idforum ON app.resposta (idforum);

-- =========================
-- embalagem
-- =========================
CREATE TABLE IF NOT EXISTS app.embalagem (
    idembalagem          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricaoembalagem   TEXT NOT NULL
);

-- =========================
-- fiscaladm
-- =========================
CREATE TABLE IF NOT EXISTS app.fiscaladm (
    idfiscaladm         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idusuario           INTEGER NOT NULL,
    responsavelfiscal   INTEGER,
    statusfiscal        INTEGER,
    numerotramiteadm    INTEGER,
    CONSTRAINT fk_fiscaladm_usuario FOREIGN KEY (idusuario) REFERENCES app.usuario (id)
);
CREATE INDEX IF NOT EXISTS idx_fiscaladm_idusuario ON app.fiscaladm (idusuario);

-- =========================
-- geraprodi
-- =========================
CREATE TABLE IF NOT EXISTS app.geraprodi (
    idgeraprodi   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataprodi     DATE,
    horaprodi     TIME,
    idusuario     INTEGER,
    statusprodi   INTEGER
);
